#!/bin/bash

set -eu

subject="$1"
shift
fqdn="$1"
shift
case "$subject"
in
  swarm)
    req_subject=/CN=docker-swarm
    dest=swarm
  ;;
  server)
    req_subject=/CN=docker-server
    dest="${fqdn}"
  ;;
  *)
    echo "'Subject' del certificado no soportado: '${subject}' valores aceptados: swarm|server"
    exit 1
  ;;
esac
alt_ips="$@"
ca_home="/var/lib/docker-ci-swarm-ca"

# creando certificados para otro fqdn
cat > "/tmp/openssl-$$.cnf" << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = ${fqdn}
DNS.2 = localhost
IP.1 = 172.17.0.1
IP.2 = 127.0.0.1
EOF
n_ip=3
for alt_ip in $alt_ips
do
  echo "IP.${n_ip} = ${alt_ip}" >> "/tmp/openssl-$$.cnf"
  n_ip="$((n_ip + 1))"
done
mkdir -pv "${ca_home}/${dest}"
chmod 750 -v "${ca_home}/${dest}"
[ -e "${ca_home}/${dest}/ca.pem" ] || cp -v "${ca_home}/ca/ca.pem" "${ca_home}/${dest}/ca.pem"
[ -e "${ca_home}/${dest}/key.pem" ] || openssl genrsa -out "${ca_home}/${dest}/key.pem" 2048
chmod -v 600 "${ca_home}/${dest}/key.pem"
openssl req -new -key "${ca_home}/${dest}/key.pem" -out "${ca_home}/${dest}/cert.csr" -subj "${req_subject}" -config "/tmp/openssl-$$.cnf"
[ -e "${ca_home}/${dest}/cert.pem" ] || openssl x509 -req -in "${ca_home}/${dest}/cert.csr" -CA "${ca_home}/ca/ca.pem" -CAkey "${ca_home}/ca/key.pem" -CAcreateserial -out "${ca_home}/${dest}/cert.pem" -days 10000 -extensions v3_req -extfile "/tmp/openssl-$$.cnf"
rm -v "${ca_home}/${dest}/cert.csr" "/tmp/openssl-$$.cnf"
